### ISSUE TITLE
[Bug]集群列表中显示集群异常，但是直接访问集群dashboad地址是可以访问的

### ISSUE THREAD

**Issue by kubeop** [1Panel-dev/KubePi#120]
**KubePi 版本**
1.6.1

**Kubernetes 版本**
1.23.6

**Bug 描述**
集群状态正常，kubepi集群列表显示集群异常，但是直接通过http://xxx.com/kubepi/dashboard/dashboard?cluster=k8s地址访问是正常的

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35365219/192952328-c944b364-20a5-4fc9-83fd-aa0de99ddc8f.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
KubePi 目前还没有适配到 1.23 大版本，我们先在本地搭建该版本的 k8s 集群并复现一下问题吧

**Comment by k8sre** [comment]
> 感谢反馈。
> KubePi 目前还没有适配到 1.23 大版本，我们先在本地搭建该版本的 k8s 集群并复现一下问题吧

我还有一个集群版本是1.24.3 的，可以正常使用

**Comment by jjzhang789** [comment]
K8S版本v1.19.3，现在也出现了这个问题。有什么办法解决吗？kubepi版本1.6.1

**Comment by wanghe-fit2cloud** [comment]
> K8S版本v1.19.3，现在也出现了这个问题。有什么办法解决吗？kubepi版本1.6.1

应该还是版本兼容的问题，推荐使用 v1.18、v1.20 和 v1.22 三个大版本。

**Comment by seaurching** [comment]
> > K8S版本v1.19.3，现在也出现了这个问题。有什么办法解决吗？kubepi版本1.6.1
> 
> 应该还是版本兼容的问题，推荐使用 v1.18、v1.20 和 v1.22 三个大版本。

这个异常是什么组建爆出来的？源码我都搜不到相关的报错。之前一直可以使用现在突然不行了，业绩这个异常
