### ISSUE TITLE
[Bug] a padding to disable MSIE and Chrome friendly error page

### ISSUE THREAD

**Issue by chenyongzhi001** [1Panel-dev/KubePi#124]
**KubePi 版本**
1.0.0

**Kubernetes 版本**
1.20.2

**Bug 描述**
kubePI配置nginx域名访问后，每次log out时提示502报错，这个问题同样也出现在demo地址中：https://demo.kubeoperator.io:8080/

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/35951080/197704038-5530c9a8-e11d-43a3-ba0c-d7625000b712.png)

2.
![24a9f7970e78c6a395524a034e3c211](https://user-images.githubusercontent.com/35951080/197704063-294b3c47-fab9-4714-9f5b-59487f9a1b09.jpg)

3.

**Comment by wanghe-fit2cloud** [comment]
Get.
