### ISSUE TITLE
[Bug]删除自建文件夹失败，报错信息“command terminated with exit code 1“

### ISSUE THREAD

**Issue by golanghu** [1Panel-dev/KubePi#127]
**KubePi 版本**

v1.6.1
**Kubernetes 版本**
v1.22.12-ko1
**Bug 描述**

**Bug 重现步骤**
1. 工作负载-pods-文件浏览器，创建文件夹之后，删除报错
![image](https://user-images.githubusercontent.com/48056671/202080663-0d170783-fdf1-450c-ae93-91688c272787.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
应该是 Pod 权限问题。可以尝试进入自建容器中操作，看是否复现上述问题。

**Comment by golanghu** [comment]
1、自建容器可以文件创建和删除正常，文件夹创建正常，但是文件夹删除报同样的问题；
2、进入容器后，执行删除文件夹命令可以成功。

**Comment by wanghe-fit2cloud** [comment]
Get.
