### ISSUE TITLE
节点亲和性/反亲和性配置无法保存[Bug]

### ISSUE THREAD

**Issue by yangandiris** [1Panel-dev/KubePi#132]
**KubePi 版本**
v1.6.1

**Kubernetes 版本**
v1.22.12-ko1

**Bug 描述**
Deplayments配置界面配置好节点亲和性规则后，点击确定保存，重新进入配置界面时发现配置并未保存，同时，通过编辑YAML文件添加亲和性规则时会生效，但是配置界面无法显示规则，而且，通过配置界面做任何修改后保存，也会导致手动添加的亲和性规则丢失。

**Bug 重现步骤(有截图更好)**
1.编辑好规则后点”确定“
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/6008810/204983652-42e36f28-6819-4bfe-91fa-2a180f30e816.png">

2.修改成功后重新进入配置界面查看，配置并未保存
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6008810/204983858-77e45c0e-3b23-475b-aed7-f3407d7abd8b.png">

3.

**Comment by wanghe-fit2cloud** [comment]
我先在本地复现一下该问题，如果存在，会在后续版本中修复该问题。

**Comment by lansefenbao** [comment]
我这里1.6.2版本，也存在此问题

**Comment by ssongliu** [comment]
v1.6.5 版本会修复上述问题。
