### ISSUE TITLE
[Bug]cronjob无法修改重启策略

### ISSUE THREAD

**Issue by jkd395** [1Panel-dev/KubePi#134]
**KubePi 版本**
v1.6.2

**Kubernetes 版本**
1.24

**Bug 描述**
cronjob重启策略无法修改

**Bug 重现步骤(有截图更好)**
1.
<img width="635" alt="1670488638369" src="https://user-images.githubusercontent.com/13271332/206398744-7d71a342-1560-4521-9935-56956531832c.png">

2.
3.

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by huangjun0910** [comment]
我也遇到同样问题 1.6.3

**Comment by ssongliu** [comment]
v1.6.5 版本会修复上述问题。
