### ISSUE TITLE
[Bug] 集群标签无法删除

### ISSUE THREAD

**Issue by zhangjijian5** [1Panel-dev/KubePi#136]
**KubePi 版本**
v1.6.2

**Kubernetes 版本**

**Bug 描述**

标签无法删除
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/43225766/210293340-e8271959-1677-4dc8-8140-6e70e7835e2b.png)

**Comment by wanghe-fit2cloud** [comment]
进入控制台的报错吗？

**Comment by ssongliu** [comment]
v1.6.5 版本会修复上述问题。
