### ISSUE TITLE
[Bug]文件浏览器特定目录无法访问

### ISSUE THREAD

**Issue by tc414103685** [1Panel-dev/KubePi#139]
**KubePi 版本**
版本: v1.6.4

**Kubernetes 版本**
v1.22.15+k3s1

**Bug 描述**
文件浏览器进入家目录失败，名称显示异常，容器/root目录，非root用户～/（如：/home/admin）

**Bug 重现步骤(有截图更好)**
1. 进入pod
2. 访问文件浏览器
3. 用户家目录显示异常，无法进入，包括root用户的/root目录，非root用户的/home/admin等目录
![image](https://user-images.githubusercontent.com/25275402/212032179-b5001f30-d501-453c-9890-37593e671a5f.png)
![image](https://user-images.githubusercontent.com/25275402/212032265-ae6f9015-39ae-40e7-b636-8bc7fb9e82a5.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by tc414103685** [comment]
请问一下这个什么时候能解决呢，比较依赖这个功能，非常的好用

**Comment by justmd5** [comment]
可能是：https://github.com/1Panel-dev/KubePi/blob/dec615cf87f410757b28a81b0af33124f07a8dbe/pkg/util/podtool/ls.go#L7 的问题，用
`--time-style="+%Y-%m-%d %H:%M:%S"` 替换 `--full-time` 可能就好了

**Comment by tc414103685** [comment]
> 可能是：
> 
> https://github.com/1Panel-dev/KubePi/blob/dec615cf87f410757b28a81b0af33124f07a8dbe/pkg/util/podtool/ls.go#L7
> 
> 的问题，用
> `--time-style="+%Y-%m-%d %H:%M:%S"`替换`--full-time`可能就好了

找到问题了，目录名和用户/用户组名称相同的情况下，获取到第一个名称后返回结果，应该获取最后一个名称
https://github.com/1Panel-dev/KubePi/blob/dec615cf87f410757b28a81b0af33124f07a8dbe/pkg/util/podtool/ls.go#L49
`strings.Index`应该改为`strings.LastIndex`

> $ sudo ls -l --full-time /
> dr-xr-x---.   9 root root 4096 2023-04-18 17:36:32.954827169 +0800 root
