### ISSUE TITLE
是否有亮色模式

### ISSUE THREAD

**Issue by hausen1012** [1Panel-dev/KubePi#140]
**请描述您的需求或者改进建议.**

**Comment by wanghe-fit2cloud** [comment]
近期还没有切换主题的研发计划。
后面版本吧，可能会加入到产品迭代中来。

**Comment by hausen1012** [comment]
好的好的，感谢回复，个人觉得亮色主题会比较清新一点

**Comment by niyuancheng** [comment]
无亮色模式



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月01日 09:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [KubeOperator/KubePi] 是否有亮色模式 (Issue #140) |

请描述您的需求或者改进建议.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by shook2012** [comment]
黑科技。

**Comment by shook2012** [comment]
但我也想要亮色主题。
