### ISSUE TITLE
[功能需求]新增一键生成CI/CD命令的功能

### ISSUE THREAD

**Issue by yongnights** [1Panel-dev/KubePi#141]
我这边通过kubepi使用Deployment部署了一个项目服务，后续更新的时候每次都需要手动更新该服务使用的镜像版本，因此，能不能在这个服务的管理界面新增一个一键生成CI/CD命令的功能，大概类似于一个curl的命令，给k8s上的该服务发送更新镜像版本的命令，不用再手动更新了，也不用通过修改yaml文件中的镜像版本进行更新了。

这种场景中，开发比较实用，提交代码到git仓库后使用jenkins进行编译打包，构造镜像推送到镜像仓库中去，此时再新增上这个CI/CD命令，就能自动实现k8s上项目服务的更新了，这中间不用手动再操作其他的了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后续版本会考虑该需求。

**Comment by wanghe-fit2cloud** [comment]
目前暂无计划和精力来支持该需求，先暂时关闭该 issue 了，望理解。
