### ISSUE TITLE
[Bug] 日志带颜色，浏览器下载的时候会转义

### ISSUE THREAD

**Issue by wanghaibo-person** [1Panel-dev/KubePi#142]
**KubePi 版本**

KubePi API V1.0

**Kubernetes 版本**

1.20.11
**Bug 描述**

如果web页面日志是带有颜色的，在web页面上下载下来颜色会自动转义
**Bug 重现步骤(有截图更好)**
1.找一个带有颜色的日志查看
![image](https://user-images.githubusercontent.com/46038902/222381690-34205496-cc0a-448d-8c66-566960135b5b.png)

2.点击下载日志
![image](https://user-images.githubusercontent.com/46038902/222381775-ebc3bb20-a28d-40d7-b140-3141cc3c7228.png)

3.查看下载的日志
所有的颜色都转义了，例如：[35m
![image](https://user-images.githubusercontent.com/46038902/222381947-95e3b72f-c7c1-4427-9636-e3c32b6bcf74.png)

**Comment by wanghe-fit2cloud** [comment]
问题已收到，感谢反馈。
