### ISSUE TITLE
[功能需求]：建议增加名称空间搜索功能

### ISSUE THREAD

**Issue by lansefenbao** [1Panel-dev/KubePi#146]
![image](https://user-images.githubusercontent.com/125638916/224252695-dce8b322-a53d-4338-87b5-c9c22f057ec3.png)
建议名称空间增加搜索功能，如果名称空间过多找起来会相对比较麻烦

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后面版本会考虑支持该需求。

**Comment by ssongliu** [comment]
v1.6.5 版本会修复上述问题。
