### ISSUE TITLE
[Question] embed同级目录的问题

### ISSUE THREAD

**Issue by tswcbyy1107** [1Panel-dev/KubePi#147]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/57310877/225631385-be3578eb-84a6-41b3-a5b2-4a62f7429869.png)
这里的go embed应该只支持同级目录吧，web在外层会报错

**Comment by ssongliu** [comment]
目录结构没问题，这里应该先进入对应的前端目录，执行 npm run build
