### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xudeheng** [1Panel-dev/KubePi#154]
**KubePi 版本**
v1.6.4

**Kubernetes 版本**
1.21.0

**Bug 描述**
登录pod超过5分钟就会出现连接超时，使用其他工具连接不会出现此情况，容器镜像没有设置连接超时时间。
超时信息如下：
******** The connection failed. Unsupported, interrupted or timed out. ********

**Bug 重现步骤(有截图更好)**
1.随意选择pod终端
2.登录进入到pod后等待5分钟
3.再次输入命令则提示超时

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。如果容器终端一直未退出会存在安全风险，因此我们设置了超时时间（5 分钟）。
