### ISSUE TITLE
[Question]在kubepi上对用户进行授权，当权限超过1年时，报错

### ISSUE THREAD

**Issue by sillyfengH** [1Panel-dev/KubePi#157]
**请描述您的问题.**
在kubepi上对用户进行授权，当权限超过1年时，报错： 

{"kind":"Status","apiVersion":"v1""metadata":{},"status":"Failunre","message":"Unauthorized","reason":"Unauthorized","code":401}

**Comment by ssongliu** [comment]
集群用户授权这里有效期默认的 1 年，这是为了安全和管理考虑，以防止长期不再需要某个用户或角色的权限，从而减少潜在的安全风险。
