### ISSUE TITLE
[Bug] Job不清理pod 

### ISSUE THREAD

**Issue by tb448479829** [1Panel-dev/KubePi#158]
**KubePi 版本**
latest

**Kubernetes 版本**
1.23.10

**Bug 描述**
手动删除Job Controller 后其创建的 pod仍然存活

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
KubePi 目前还没有适配过 v1.23 版本的 K8s 集群，可能存在兼容性问题。
我们后续版本尝试复现一下该问题。
