### ISSUE TITLE
无法获取到值

### ISSUE THREAD

**Issue by jiahuat** [1Panel-dev/KubePi#159]
https://github.com/1Panel-dev/KubePi/blob/3bf8f69518e6f943213f8f39ca96bea4239b8cce/internal/api/v1/chart/chart.go#L228

两个问题。
问题1：
使用版本tag v1.6.4 在分页查询需要pageNum 和 pageSize时，无法通过Values.GetInt获取；可以使用 URLParamInt获取；
问题2：
获取pageNum和pageSize时，有未处理的错误

**Comment by wanghe-fit2cloud** [comment]
v1.6.5 版本会修复上述问题。
