### ISSUE TITLE
[bug] LDAP导入用户报错 user is not found

### ISSUE THREAD

**Issue by cnwelee** [1Panel-dev/KubePi#161]
之前版本一直可以正常使用，最近发现一些新增的LDAP用户在系统里没有所以试着”同步用户“结果报错了
![报错如图](https://s2.loli.net/2023/05/29/xGPEzNdVaT9Fo6n.png)
点”测试连接“也是报这个错，
已有的老用户可以正常登录，这个页面点”测试登录“也可以正常通过测试

目前版本已经是v1.6.4了

**Comment by cnwelee** [comment]
问题：之前版本上一直用的好好的，不知道哪次升级之后就没法“同步用户”了

**Comment by wanghe-fit2cloud** [comment]
提示信息显示用户不存在，大概率是过滤规则没有筛选到用户。

**Comment by cnwelee** [comment]
关键是同样的配置没有任何变动，退回到老版本就可以正常用了……
