### ISSUE TITLE
请适配k8s v1.28

### ISSUE THREAD

**Issue by ztdawang** [1Panel-dev/KubePi#182]
# 1.22版本，实在太老了
        k8s.io/api v0.22.2
	k8s.io/apiextensions-apiserver v0.22.2
	k8s.io/apimachinery v0.22.2
	k8s.io/cli-runtime v0.22.1
	k8s.io/client-go v0.22.2
	k8s.io/klog/v2 v2.9.0
	k8s.io/kubectl v0.22.1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
