### ISSUE TITLE
应用仓库无法获取应用列表

### ISSUE THREAD

**Issue by tangrongxing** [1Panel-dev/KubePi#183]
使用kubeoperator创建的k8s集群v1.22版本，helm_v3版本，进到kubepi添加chart仓库地址后，一直在加载列表。
![屏幕截图 2023-11-06 034701](https://github.com/1Panel-dev/KubePi/assets/79203492/71699068-e763-4ce3-8039-44cb690c7623)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们近期在本地环境复现一下上述问题。
