### ISSUE TITLE
[Question] 体验端口

### ISSUE THREAD

**Issue by hsmbs** [1Panel-dev/KubePi#186]
飞致云的产品我们用的不少，体验都很棒。
第一次发现还有k8s的面板。
这个面板有没有体验demo？

**Comment by wanghe-fit2cloud** [comment]
> 飞致云的产品我们用的不少，体验都很棒。 第一次发现还有k8s的面板。 这个面板有没有体验demo？

暂无演示环境。
KubePi 只涉及到一条 docker run 命令，资源占用也非常小，可以尝试手动部署。
> 1Panel 应用商店中也支持一键部署。
