### ISSUE TITLE
[功能需求]新增支持阿里云个人版镜像仓库的功能

### ISSUE THREAD

**Issue by lip215591601** [1Panel-dev/KubePi#187]
我这边通过kubepi以DockerRegistry的类型添加镜像仓库，地址写的是：registry.cn-beijing.aliyuncs.com，镜像下载地址写的是：registry.cn-beijing.aliyuncs.com/xxxx，输入了正确的用户名密码，可以正常创建镜像仓库。但是在点击镜像仓库查看镜像列表时报错：Get "/v2/_catalog?n=10": unsupported protocol scheme ""。并且我在创建deployment时无法使用这个新创建的镜像仓库。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by yela8824** [comment]
registry.cn-beijing.aliyuncs.com->https://registry.cn-beijing.aliyuncs.com 
registry.cn-beijing.aliyuncs.com/xxxx->https://registry.cn-beijing.aliyuncs.com/xxxx
可以解决这个问题。但是我遇到了另一个问题，一直报unauthorized: authentication required。
我输入的用户名和密码是正确的，至少我docker login --username=xxx registry.cn-hangzhou.aliyuncs.com能行，但这个就是一直登录不上。

**Comment by lip215591601** [comment]
好的，一会儿我试试

**Comment by lip215591601** [comment]
我也是报这个错误！！！

**Comment by wanghe-fit2cloud** [comment]
目前暂无计划和精力来支持该需求，先暂时关闭该 issue 了，望理解。
