### ISSUE TITLE
添加一份二次开发文档

### ISSUE THREAD

**Issue by liutao124** [1Panel-dev/KubePi#189]
建议在项目的介绍中添加一份二开的指导章节，介绍一下架构，原理之类的

**Comment by eryajf** [comment]
同样期待，这样能让更多人参与进来
包括这个项目的未来规划之类的
我基本上了解了市面上大多数的k8s多集群管理工具，最后发下kubepi这颗遗珠，衷心希望这个项目越来越好，让更多人知道
