### ISSUE TITLE
[Bug] 自建账号访问集群报500

### ISSUE THREAD

**Issue by yeeeee7** [1Panel-dev/KubePi#200]
**KubePi 版本**
v1.6.5

**Kubernetes 版本**
v1.23.4

**Bug 描述**
admin账号打开集群正常，使用创建的账号且设置的自定义namespace权限后，使用创建的账号就访问集群就报错
{ "code": 500, "message": "", "success": false }

**Bug 重现步骤(有截图更好)**
1.kubepi使用主机网络部署
2.创建新账号，并使用自定义namespace授权
3.使用创建的账号就访问集群就报错

**Comment by wanghe-fit2cloud** [comment]
存在权限问题，除了命名空间权限外，还需要 node 节点等权限。建议使用具有 admin 权限的账号来导入集群。
