### ISSUE TITLE
[Bug] 文件浏览器里面部分文件无法下载

### ISSUE THREAD

**Issue by xudingjun3131** [1Panel-dev/KubePi#202]
**KubePi 版本**
 v1.7.0

**Kubernetes 版本**
v1.23.17

**Bug 描述**
在  工作负载-pod-文件浏览器里面点击文件无法查看下载，报错“invalid character '-' in numeric literal”
然后点击文件下载，下载后的tar包提示文件损坏，但是有部分文件又可以正常下载使用。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/1Panel-dev/KubePi/assets/16241230/4b4fd473-7ff9-4419-b6dd-c396e0eb9a6d)
![image](https://github.com/1Panel-dev/KubePi/assets/16241230/d9fc0504-21c3-4b34-9e3a-4e9e44e68cd8)

**Comment by shaxiaozz** [comment]
@wanghe-fit2cloud 看起来是这里有问题了。前端去请求后端接口，数据提交给的是‘multipart/form-data’表单数据，但是后端的接口是基于JSON数据解析。因此后端接口error message出现“invalid character '-' in numeric literal”。

前端代码：web/dashboard/src/plugins/request.js
```
119   export const postFile= (url,data, params,loading) => {
120     return promise(request({url: url, method: "post",data: data,params:params, headers:{"Content-Type":"multipart/form-data"},timeout:600000}), loading)
121   }
```
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/2eea8fe5-c5a2-4d6f-8290-b50c80f621d9)


后端代码（handler.OpenFile()）：internal/api/v1/file/file.go
```
		if err := ctx.ReadJSON(&req); err != nil {
			ctx.StatusCode(iris.StatusBadRequest)
			ctx.Values().Set("message", err.Error())
			return
		}
```
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/70f27189-ba34-4c8e-9725-bbe3b176dc69)

同时观察到前端postFile方法，创建文件，更新文件，查看文件，上传文件都是通过这个方法请求后端。后端入参数据类型都是json数据。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已修复该问题。
