### ISSUE TITLE
关于Kubepi在Kubernetes集群部署多实例的问题

### ISSUE THREAD

**Issue by devops-jiangxl** [1Panel-dev/KubePi#203]
Kubepi在Kubernetes中使用Deployment进行部署，并开启了多个副本，其中只有一个副本可以运行成功，其他均运行失败，报错内容如下，请问如何解决：
goroutine 1 [running]:
github.com/KubeOperator/kubepi/internal/server.(*KubePiServer).setUpDB(0xc001d54940)
github.com/KubeOperator/kubepi/internal/server/server.go:121 +0x11f
github.com/KubeOperator/kubepi/internal/server.(*KubePiServer).bootstrap(0xc001d54940)
github.com/KubeOperator/kubepi/internal/server/server.go:294 +0x45
github.com/KubeOperator/kubepi/internal/server.NewKubePiSerer({0xc001a5fd18, 0x3, 0x0?})
github.com/KubeOperator/kubepi/internal/server/server.go:89 +0x1be
github.com/KubeOperator/kubepi/internal/server.Listen(0x4e0ce70, {0xc001a5fd18?, 0x0?, 0x0?})
github.com/KubeOperator/kubepi/internal/server/server.go:320 +0x30
main.glob..func1(0x7e890e0?, {0x258d3f5?, 0x0?, 0x0?})
./main.go:68 +0x1c5
github.com/spf13/cobra.(*Command).execute(0x7e890e0, {0xc00011e200, 0x0, 0x0})
github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x7e890e0)
github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
./main.go:88 +0x25

******** The connection failed. Unsupported, interrupted or timed out. ********

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。KubePi 目前不支持集群和高可用部署。
