### ISSUE TITLE
内存使用量显示不正常的问题

### ISSUE THREAD

**Issue by tiansin** [1Panel-dev/KubePi#205]
k8s版本v1.23.15

<img width="767" alt="Screenshot 2024-05-31 at 11 48 36" src="https://github.com/1Panel-dev/KubePi/assets/4232281/83abfd76-7d13-4e1c-adaa-833369d0c880">

**Comment by shaxiaozz** [comment]
@tiansin kubepi版本多少？

**Comment by tiansin** [comment]
@shaxiaozz kubepi 版本: v1.7.0

**Comment by shaxiaozz** [comment]
复现不出来

**Comment by tiansin** [comment]
@shaxiaozz 我是拿最新版本的kubekey装的,不会是因为这个吧.

**Comment by shaxiaozz** [comment]
@tiansin 镜像v1.7.0是正常的

**Comment by tiansin** [comment]
![1718770322270](https://github.com/1Panel-dev/KubePi/assets/4232281/e13eb752-5c47-4211-af8a-4faa08fcccbe)
@shaxiaozz 但我这就是不正常,奇怪了... 这问题有没有什么排查方法呢?

**Comment by shaxiaozz** [comment]
@tiansin 你4个节点渲染都不行吗？

**Comment by tiansin** [comment]
@shaxiaozz 节点用起来没有问题,都能正常使用的.就是显示的数据不正常

**Comment by tiansin** [comment]
<img width="170" alt="Screenshot 2024-06-19 at 12 22 19" src="https://github.com/1Panel-dev/KubePi/assets/4232281/7beca768-7a08-4c3e-9934-404e2187fa50">
节点列表里边的显示也是错的

**Comment by tiansin** [comment]
@shaxiaozz 

`/kubepi/api/v1/proxy/prod-k8s/k8s/api/v1/nodes?search=true&pageNum=1&pageSize=10`
这个接口返回的部分json数据:

正常显示的:
```
                "allocatable": {
                    "cpu": "4",
                    "ephemeral-storage": "483173420666",
                    "hugepages-1Gi": "0",
                    "hugepages-2Mi": "0",
                    "memory": "16162352Ki",
                    "pods": "110"
                },
                "capacity": {
                    "cpu": "4",
                    "ephemeral-storage": "524276716Ki",
                    "hugepages-1Gi": "0",
                    "hugepages-2Mi": "0",
                    "memory": "16264752Ki",
                    "pods": "110"
                },
```
不不正常的:
```
                "allocatable": {
                    "cpu": "3600m",
                    "ephemeral-storage": "208394220Ki",
                    "hugepages-1Gi": "0",
                    "hugepages-2Mi": "0",
                    "memory": "7265135610",
                    "pods": "110"
                },
                "capacity": {
                    "cpu": "4",
                    "ephemeral-storage": "208394220Ki",
                    "hugepages-1Gi": "0",
                    "hugepages-2Mi": "0",
                    "memory": "8007220Ki",
                    "pods": "110"
                },
```

**Comment by shaxiaozz** [comment]
@tiansin 我这里查看是正常的
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/20aca067-ea1d-4c35-9fff-ef7ca712905e)

**Comment by tiansin** [comment]
@shaxiaozz 我去分析了下代码,发现原因是我这边返回的**usage.memory**和**status.allocatable.memory**属性返回的是byte类型数值.
https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/business/cluster/nodes/index.vue#L172

导致下边的两个函数处理有问题.
https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/filters/index.js#L81
https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/utils/unitConvert.js#L15

**Comment by tiansin** [comment]
> @tiansin 你可以查看下你的metrics-server版本是多少吗

<img width="276" alt="image" src="https://github.com/1Panel-dev/KubePi/assets/4232281/c22a8a27-85a8-485e-85c4-4aa9edb4ccdf">

**Comment by tiansin** [comment]
> @tiansin 你可以按照以下方法使用curl请求k8s api-server接口，测试验证吗？
> 
> _**Step 1**_
> 
> ```
> cd ~/.kube/
> cat config | grep certificate-authority-data | awk '{print $2}' | base64 -d > ca.crt
> cat config | grep client-certificate-data | awk '{print $2}' | base64 -d > client.crt
> cat config | grep client-key-data | awk '{print $2}' | base64 -d > client.key
> APISERVER=$(cat config | grep server | awk '{print $2}')
> ```
> 
> _**Step 2**_
> 
> ```
> curl --cert ./client.crt --cacert ./ca.crt --key ./client.key $APISERVER/apis/metrics.k8s.io/v1beta1/nodes 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43721571/341353003-5c51cf63-593d-41e0-b8da-c8fbc167a503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDQyNjMsIm5iZiI6MTcxODk0Mzk2MywicGF0aCI6Ii80MzcyMTU3MS8zNDEzNTMwMDMtNWM1MWNmNjMtNTkzZC00MWUwLWI4ZGEtYzhmYmMxNjdhNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA0MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjM3YzZiMTFmNTEzZmZlZjdkOGNmYzdhMDY4MTg2OGQ1YmMzYzI1M2Y1ODQ5YjQ5Y2RhNjg4NjFiOGI0NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mF-cD2Rmr1zt9jhpbRrrr-FYi7H4F34MBrqrO_OZ34Q)
> 
> 我的metrics-server版本是v0.5.0

```
{
  "kind": "NodeMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {

  },
  "items": [
    {
      "metadata": {
        "name": "k8s-master",
        "creationTimestamp": "2024-06-21T04:35:54Z",
        "labels": {
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/os": "linux",
          "kubernetes.io/arch": "amd64",
          "kubernetes.io/hostname": "k8s-master",
          "kubernetes.io/os": "linux",
          "node-role.kubernetes.io/control-plane": "",
          "node-role.kubernetes.io/master": "",
          "node.kubernetes.io/exclude-from-external-load-balancers": ""
        }
      },
      "timestamp": "2024-06-21T04:35:42Z",
      "window": "20s",
      "usage": {
        "cpu": "149009900n",
        "memory": "3203244Ki"
      }
    },
    {
      "metadata": {
        "name": "k8s-node1",
        "creationTimestamp": "2024-06-21T04:35:54Z",
        "labels": {
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/os": "linux",
          "kubernetes.io/arch": "amd64",
          "kubernetes.io/hostname": "k8s-node1",
          "kubernetes.io/os": "linux",
          "node-role.kubernetes.io/worker": ""
        }
      },
      "timestamp": "2024-06-21T04:35:41Z",
      "window": "20s",
      "usage": {
        "cpu": "271930850n",
        "memory": "16294076Ki"
      }
    },
    {
      "metadata": {
        "name": "k8s-node2",
        "creationTimestamp": "2024-06-21T04:35:54Z",
        "labels": {
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/os": "linux",
          "kubernetes.io/arch": "amd64",
          "kubernetes.io/hostname": "k8s-node2",
          "kubernetes.io/os": "linux",
          "node-role.kubernetes.io/worker": ""
        }
      },
      "timestamp": "2024-06-21T04:35:38Z",
      "window": "10s",
      "usage": {
        "cpu": "166265u",
        "memory": "16454776Ki"
      }
    },
    {
      "metadata": {
        "name": "k8s-node3",
        "creationTimestamp": "2024-06-21T04:35:54Z",
        "labels": {
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/os": "linux",
          "kubernetes.io/arch": "amd64",
          "kubernetes.io/hostname": "k8s-node3",
          "kubernetes.io/os": "linux",
          "node-role.kubernetes.io/worker": ""
        }
      },
      "timestamp": "2024-06-21T04:35:44Z",
      "window": "20s",
      "usage": {
        "cpu": "190991150n",
        "memory": "17670484Ki"
      }
    }
  ]
}
```

**Comment by shaxiaozz** [comment]
@tiansin 看了。kubepi不会响应数据，node memory的数据都是从apiserver获取的。对应两个接口
https://192.168.56.101:6443/api/v1/nodes?search=true&pageNum=1&pageSize=100
https://192.168.56.101:6443/apis/metrics.k8s.io/v1beta1/nodes

直接原封不动的将apiserver获取到数据返回的

**Comment by tiansin** [comment]
@shaxiaozz 这个我也分析过了,返回的数据是对的,只是我这里返回的是纯数字的Byte数值,而不是带**Ki**这种.
然后下边的两个格式化函数,一个未处理未返回,另一个直接`Number(value)`返回

这张图就是直接`Number(value)`返回,所以是个很大的值.
![image](https://github.com/1Panel-dev/KubePi/assets/4232281/bec5d7db-1cb8-43fe-9d90-89cddb88b63e)

这张图就是未处理,导致`Gi`前面的值都是空的.
![image](https://github.com/1Panel-dev/KubePi/assets/4232281/6e33e58e-edff-4370-9a06-5ea3e92e8189)

> @shaxiaozz 我去分析了下代码,发现原因是我这边返回的**usage.memory**和**status.allocatable.memory**属性返回的是byte类型数值.
> 
> https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/business/cluster/nodes/index.vue#L172
> 
> 导致下边的两个函数处理有问题.
> 
> https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/filters/index.js#L81
> 
> 
> https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/utils/unitConvert.js#L15

**Comment by shaxiaozz** [comment]
@tiansin 你的节点是不是有超分配的情况。k8s的接口是会带上单位返回的，不带单位返回本来就是一个异常

**Comment by shaxiaozz** [comment]
@tiansin 你可以请求/api/v1/nodes?search=true&pageNum=1&pageSize=100看看allocatable.memory是否不存在单位

**Comment by tiansin** [comment]
> @shaxiaozz
> 
> `/kubepi/api/v1/proxy/prod-k8s/k8s/api/v1/nodes?search=true&pageNum=1&pageSize=10` 这个接口返回的部分json数据:
> 
> 正常显示的:
> 
> ```
>                 "allocatable": {
>                     "cpu": "4",
>                     "ephemeral-storage": "483173420666",
>                     "hugepages-1Gi": "0",
>                     "hugepages-2Mi": "0",
>                     "memory": "16162352Ki",
>                     "pods": "110"
>                 },
>                 "capacity": {
>                     "cpu": "4",
>                     "ephemeral-storage": "524276716Ki",
>                     "hugepages-1Gi": "0",
>                     "hugepages-2Mi": "0",
>                     "memory": "16264752Ki",
>                     "pods": "110"
>                 },
> ```
> 
> 不不正常的:
> 
> ```
>                 "allocatable": {
>                     "cpu": "3600m",
>                     "ephemeral-storage": "208394220Ki",
>                     "hugepages-1Gi": "0",
>                     "hugepages-2Mi": "0",
>                     "memory": "7265135610",
>                     "pods": "110"
>                 },
>                 "capacity": {
>                     "cpu": "4",
>                     "ephemeral-storage": "208394220Ki",
>                     "hugepages-1Gi": "0",
>                     "hugepages-2Mi": "0",
>                     "memory": "8007220Ki",
>                     "pods": "110"
>                 },
> ```

正常显示的那个是我的一个老服务器,不正常显示的是我最近新搭的服务器.


@shaxiaozz 并没有超分配,用kubekey弄出来就是这样,这个我之前不是发出来了了嘛

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已修复该问题。

**Comment by tiansin** [comment]
> v1.8.0 版本已修复该问题。

感谢,另外的那个显示问题可以也修复一下吗?

![image](https://github.com/user-attachments/assets/dbe78199-af93-4427-b6ac-f00561556529)

**Comment by tiansin** [comment]
@shaxiaozz @wanghe-fit2cloud  这里边 **giMemoryFormat** 和 **miMemoryFormat** 函数也有处理不了byte值

https://github.com/1Panel-dev/KubePi/blob/0209ad00eed505f4f1b1c5bca2942708665984b8/web/dashboard/src/filters/index.js#L81
