### ISSUE TITLE
[Bug] 在macos上运行，无法启动终端

### ISSUE THREAD

**Issue by calvinlee1** [1Panel-dev/KubePi#206]
**KubePi 版本**
master主线

**Kubernetes 版本**
1.29.3

**Bug 描述**
在macos上运行，无法启动终端

**Bug 重现步骤(有截图更好)**
![image](https://github.com/1Panel-dev/KubePi/assets/26641000/9831e901-d869-45ae-8e6d-d25f0821945f)
![image](https://github.com/1Panel-dev/KubePi/assets/26641000/96aafbda-07c6-453f-9f01-a3123ace1e02)

**Comment by calvinlee1** [comment]
输出的log如下：
![image](https://github.com/1Panel-dev/KubePi/assets/26641000/7160f4e1-edc4-4b05-be75-f062e170ea06)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们尚未适配 macOS，目前仅支持在 Linux 服务上运行。
