### ISSUE TITLE
[Bug] 无法查看失败的 Pod 日志

### ISSUE THREAD

**Issue by SuperNiu666** [1Panel-dev/KubePi#208]
**KubePi 版本**
v1.7.0

**Kubernetes 版本**
v1.28.3

**Bug 描述**
当 Pod 正常启动时没问题；
当 Pod 启动异常时，无法查看日志，详见下图

**Bug 重现步骤(有截图更好)**
![image](https://github.com/1Panel-dev/KubePi/assets/78398920/d67d4394-b22a-4fea-8096-25b0b0856161)
![image](https://github.com/1Panel-dev/KubePi/assets/78398920/b20d56f1-a80b-47b7-9a72-927c34192964)

**Comment by shaxiaozz** [comment]
@SuperNiu666 这个报错是正常的。因为容器无法维持websocket连接，所以就会关闭连接。至于你说的没有日志，应该是你在点击查看日志时刚好只有哪一条。

我这边测试是正常的
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/0ae5aff4-9717-4063-91c4-abd11fc136df)

**Comment by SuperNiu666** [comment]
> @SuperNiu666 这个报错是正常的。因为容器无法维持websocket连接，所以就会关闭连接。至于你说的没有日志，应该是你在点击查看日志时刚好只有哪一条。
> 
> 我这边测试是正常的 ![image](https://private-user-images.githubusercontent.com/43721571/341014287-0ae5aff4-9717-4063-91c4-abd11fc136df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTE1NDQsIm5iZiI6MTcxODc5MTI0NCwicGF0aCI6Ii80MzcyMTU3MS8zNDEwMTQyODctMGFlNWFmZjQtOTcxNy00MDYzLTkxYzQtYWJkMTFmYzEzNmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEwMDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDQ2NzE4YTlkZGQ3ZTZkY2IzOTQ4NGU4OWE5ZDhmZGFhNTAxMGQxNTAyNWIzMWQ4MDViZjZjZDM2YzNhYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.exPCxXmyb2ZRudfbApZlhpGJ3AhurTa0RK1S9V1Enqw)

我又测试了下，图中包含 测试使用的 yaml，Pod 状态，以及命令行日志输出，以及另一张图内容是 kubePi 的日志输出
![image](https://github.com/1Panel-dev/KubePi/assets/78398920/eb6a266c-1e40-4c6c-b1cf-44f260a96413)
![image](https://github.com/1Panel-dev/KubePi/assets/78398920/665f1811-94ba-45cb-81ac-764204bf12b5)


能理解您的意思，但我想的是，根据 kubectl logs 输出内容来看：
当容器运行时会建立 websocket 链接持续监听日志；
当容器退出时会输出 容器之前已经输出的日志。
而 kubePi 似乎没做到，输出 失败容器 之前已经输出的日志，
图中的测试，无论我刷新多少次，
kubectl logs 始终能正常输出
start
-----
exit
而 kubePi 如图始终只能输出
start


******** The connection failed. Unsupported, interrupted or timed out. ********

其中有效输出是 start ，少了后面的内容，这个会是什么问题呢

**Comment by shaxiaozz** [comment]
@SuperNiu666 kubernetes v1.23.15视乎复现不出来你的问题
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/10f94b58-6f56-40fe-b2a4-ec3ec3c57f74)

**Comment by shaxiaozz** [comment]
@SuperNiu666 同样的，我用k8s v.1.28.2版本也没有复现
![image](https://github.com/1Panel-dev/KubePi/assets/43721571/e31e7940-8ab3-456e-a86f-c19e346bb899)

**Comment by SuperNiu666** [comment]
> @SuperNiu666 同样的，我用k8s v.1.28.2版本也没有复现 ![image](https://private-user-images.githubusercontent.com/43721571/341297564-e31e7940-8ab3-456e-a86f-c19e346bb899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzI1MTgsIm5iZiI6MTcxODg3MjIxOCwicGF0aCI6Ii80MzcyMTU3MS8zNDEyOTc1NjQtZTMxZTc5NDAtOGFiMy00NTZlLWE4NmYtYzE5ZTM0NmJiODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4MzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NzMzZGI5NWMyYzUyOGEwOThiZDM0OWIyODkwNGY5MjU2YTc0N2ExMTdmNjc4ZmRjZWVhYWQ4ZGVjOGU1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wVvNx8c4a2Mfj5fmu7pxBYajOVtBtyCr1B8rvdFqO0Q)

在多次测试后定位到，由于 kubepi 所在云主机上有多个服务，使用了 nginx 转发，在 location 中添加
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
即可，最后，感谢您的耐心回复😄

**Comment by shaxiaozz** [comment]
you can close this issues~
