### ISSUE TITLE
[Bug] 新增集群无法纳管成功

### ISSUE THREAD

**Issue by pandihao** [1Panel-dev/KubePi#242]
**KubePi 版本**
v1.7.0

**Kubernetes 版本**
v.1.19.4

**Bug 描述**
1 . 新增集群出现加入失败

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/624d4454-80f2-4938-a48c-e7369633fa19)

2.
3.

**Comment by wanghe-fit2cloud** [comment]
需要查看一下 KubePi 容器日志。
