### ISSUE TITLE
有rest api可以调用吗

### ISSUE THREAD

**Issue by kinbod** [1Panel-dev/KubePi#252]
1.如果应用有更新或者新的镜像是否可以提示。
2.是否可以提供api接口进行应用批量更新。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求是指应用商店中部署的应用吗？

**Comment by kinbod** [comment]
除了应用商店，手动部署的能支持吗

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: wanghe ***@***.***>
发送时间: Monday, July 29, 2024 5:01:19 PM
收件人: 1Panel-dev/KubePi ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [1Panel-dev/KubePi] 有rest api可以调用吗 (Issue #252)


感谢反馈，上述需求是指应用商店中部署的应用吗？

―

**Comment by wanghe-fit2cloud** [comment]
我们已提供了 KubePi 管理页面的接口文档，您可以通过以下地址访问：/kubepi/swagger/index.html。至于 K8s 集群及 Chat 商店相关的接口文档，目前还没有计划提供，感谢理解。

**Comment by kinbod** [comment]
好的，感谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: wanghe ***@***.***>
发送时间: Monday, July 29, 2024 5:27:43 PM
收件人: 1Panel-dev/KubePi ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [1Panel-dev/KubePi] 有rest api可以调用吗 (Issue #252)


我们已提供了 KubePi 管理页面的接口文档，您可以通过以下地址访问：/kubepi/swagger/index.html。至于 K8s 集群及 Chat 商店相关的接口文档，目前还没有计划提供，感谢理解。

―
