### ISSUE TITLE
连接AWS EKS集群[Bug]

### ISSUE THREAD

**Issue by minchell168** [1Panel-dev/KubePi#76]
**KubePi 版本**
最新的master分支

**Kubernetes 版本**
1.21

**Bug 描述**
直接使用kubepi添加AWS EKS集群，添加不了，会报错

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
1、使用哪种方式添加的eks集群
2、错误信息

**Comment by minchell168** [comment]
kubeconfig形式添加的eks集群，没有错误信息，不提示，集群并不是通过KubeOperator建的，而是通过AWS 操作台建的
![image](https://user-images.githubusercontent.com/74719974/164393768-21f41ce6-dc4c-4283-b9a0-d46629eb09fe.png)

**Comment by minchell168** [comment]
> 1、使用哪种方式添加的eks集群 2、错误信息

kubeconfig形式添加的eks集群，没有错误信息，不提示，集群并不是通过KubeOperator建的，而是通过AWS 操作台建的
![image](https://user-images.githubusercontent.com/74719974/164394223-4393122e-dd36-47ff-bc5d-819dbfb78fa4.png)

**Comment by minchell168** [comment]
> 1、使用哪种方式添加的eks集群 2、错误信息

![image](https://user-images.githubusercontent.com/74719974/164395035-71e39d61-380d-4596-9c8d-aba4aa36f53c.png)
导入的镜像如果使用docker hub里面的镜像，则会提示这个错误

**Comment by wanghe-fit2cloud** [comment]
目前暂无精力适配 AWS EKS 集群，暂时关闭此 issue，望理解。
